spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/parkalot
    username: postgres
    password: Princecharles@99
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    
server:
  port: 8080
  
